### PR TITLE
Add PR reviews to score calculation

### PR DESCRIPTION
**Pull request by sdepold**
With this PR we are now honouring pull request reviews as well. Right now I only count the Approval of a PR but we could also change it to anything else if you feel like that is making sense.

Before
```
Overall stats
-------------
WikiRik: 42% (total: 91, pr: 68, issues: 0, comments: 23)
fzn0x: 18% (total: 41, pr: 34, issues: 0, comments: 7)
ephys: 15% (total: 34, pr: 18, issues: 0, comments: 16)
sdepold: 13% (total: 30, pr: 24, issues: 0, comments: 6)
mmkal: 4% (total: 10, pr: 8, issues: 0, comments: 2)
evanrittenhouse: 2% (total: 6, pr: 4, issues: 0, comments: 2)
sushantdhiman: 1% (total: 4, pr: 4, issues: 0, comments: 0)
```

After
```
Overall stats
-------------
WikiRik: 57% (total: 296, pr: 68, issues: 0, reviews: 204, comments: 24)
sdepold: 16% (total: 85, pr: 24, issues: 0, reviews: 55, comments: 6)
ephys: 10% (total: 56, pr: 18, issues: 0, reviews: 22, comments: 16)
fzn0x: 10% (total: 54, pr: 34, issues: 0, reviews: 13, comments: 7)
mmkal: 2% (total: 12, pr: 8, issues: 0, reviews: 2, comments: 2)
evanrittenhouse: 1% (total: 7, pr: 4, issues: 0, reviews: 1, comments: 2)
sushantdhiman: 0% (total: 4, pr: 4, issues: 0, reviews: 0, comments: 0)
```

### CODE REVIEW

**Comment by WikiRik** [comment]
Can we ignore the renovate PRs for this?

**Comment by sdepold** [comment]
We could given that it's still work however, I wonder if we should. But I can see where you are coming from since it's less complex than other reviews.

**Comment by WikiRik** [comment]
Maybe we can add an `reward-ignore` label or whatever and tell renovate to apply that automatically so we can remove it when it is more than a minute work. Since I do not believe I should get 10+% extra for that little effort.

**Comment by sdepold** [comment]
I'm fine with both really. @ephys any opinion? If we all agree that dependency updates should be counted as contributions to the project at all, I would probably rather change the logic than labeling all those PRs manually :D

**Comment by ephys** [comment]
We could apply reward-ignore, but we also could tell renovate to auto-merge :)

**Comment by WikiRik** [comment]
I have looked into that in the past, I believe we needed a separate GitHub Action to discard the need for a review before merging

**Comment by WikiRik** [comment]
Let's look into that later this week and merge this PR afterwards for next quarter

**Comment by WikiRik** [comment]
renovate seems to auto-merge things now, I think we should be good to go once conflicts have been resolved

**Comment by ephys** [comment]
I think we shouldn't include reviews in the score since we already include comments. It's basically going to double the score of comments

**Comment by fzn0x** [comment]
I see, so reviews also recognized as comments

**Comment by WikiRik** [comment]
Ah, I thought this PR was because reviews weren't checked. But you think that reviews with a general comment did count? In that case that's just a small behaviour change for maintainers

**Pull request closed without merging**
