### PR TITLE
Increase weight of funded PRs

### PR DESCRIPTION
**Pull request by sdepold**
With this PR, we increase the importance and weight of implementing funded work. Each PR that is labelled with "funded" will be scored 5 times higher than normal PRs or 10 times higher than a commented PR.

### CODE REVIEW

**Comment by sdepold** [comment]
Before:

```
WikiRik: 43% (total: 83, pr: 60, issues: 0, comments: 23)
fzn0x: 21% (total: 41, pr: 34, issues: 0, comments: 7)
ephys: 17% (total: 34, pr: 18, issues: 0, comments: 16)
sdepold: 7% (total: 14, pr: 8, issues: 0, comments: 6)
mmkal: 5% (total: 10, pr: 8, issues: 0, comments: 2)
evanrittenhouse: 3% (total: 6, pr: 4, issues: 0, comments: 2)
sushantdhiman: 2% (total: 4, pr: 4, issues: 0, comments: 0)
```


After:

```
Overall stats
-------------
WikiRik: 42% (total: 91, pr: 68, issues: 0, comments: 23)
fzn0x: 18% (total: 41, pr: 34, issues: 0, comments: 7)
ephys: 15% (total: 34, pr: 18, issues: 0, comments: 16)
sdepold: 13% (total: 30, pr: 24, issues: 0, comments: 6)
mmkal: 4% (total: 10, pr: 8, issues: 0, comments: 2)
evanrittenhouse: 2% (total: 6, pr: 4, issues: 0, comments: 2)
sushantdhiman: 1% (total: 4, pr: 4, issues: 0, comments: 0)
```

Currently only 2 of my PRs are marked as funded. That means we reduce 2*2 points from my score and add 2*10 == 6 + (8-4+20) = 30

**Comment by WikiRik** [comment]
Would it be possible to extend the list of users to include all users that have worked on funded issues? Or do we want to give them a separate bounty?

**Comment by sdepold** [comment]
You mean non-team members?

**Comment by WikiRik** [comment]
Yup!

**Comment by sdepold** [comment]
So that we could hand out money to "outsiders"? I guess for that we would need to change the fundamental approach of the script since it is currently starting from our team and finds data for the members. I didn't even consider this approach so far. :D

**Comment by sdepold** [comment]
Fine with merging this without the other users?

**Comment by sdepold** [comment]
I guess we can extend it if concrete need arises?

**Comment by WikiRik** [comment]
Sure!

**Review by WikiRik — APPROVED** [review]

**Comment by sdepold** [comment]
@WikiRik I just added support for "external" people and threat treat them as if they would be team members.
For testing purposes, I added the label funded to https://github.com/sequelize/sequelize/pull/15087 hence we see 10 points for this and another 2 for https://github.com/sequelize/sequelize/pull/14930

```
Overall stats
-------------
WikiRik: 40% (total: 92, pr: 68, issues: 0, comments: 24)
fzn0x: 17% (total: 41, pr: 34, issues: 0, comments: 7)
ephys: 14% (total: 34, pr: 18, issues: 0, comments: 16)
sdepold: 13% (total: 30, pr: 24, issues: 0, comments: 6)
sfc-gh-dgadomski: 5% (total: 12, pr: 12, issues: 0, comments: 0)
mmkal: 4% (total: 10, pr: 8, issues: 0, comments: 2)
evanrittenhouse: 2% (total: 6, pr: 4, issues: 0, comments: 2)
sushantdhiman: 1% (total: 4, pr: 4, issues: 0, comments: 0)
```

**Review by WikiRik — APPROVED** [review]
I looked through it quickly and seems good. It also works for you so that helps

**Pull request merged**
